/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-5-13: 13h: 1m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.sats: 1(line=1, offs=1) -- 22(line=1, offs=22)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
} postiats_tysum_0 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(b) atslab__0 ;
} postiats_tysum_1 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
} postiats_tysum_2 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_print_string)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
#if(0)
ATSextern()
atstype_boxed
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_sats__maybe_bind__0(atstype_boxed, atstype_funptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_sats__maybe_show__1(atstype_boxed, atstype_funptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
/*
/home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 104(line=5, offs=28) -- 183(line=8, offs=27)
*/
/*
local: 
global: maybe_bind$0$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(3838), b(3839)
tmparg = S2Evar(a(3838)), S2Evar(b(3839))
tmpsub = None()
*/
atstype_boxed
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_sats__maybe_bind__0(atstype_boxed arg0, atstype_funptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstype_boxed) ;
ATStmpdec(tmp1, atstyvar_type(a)) ;
ATStmpdec(tmp2, atstyvar_type(b)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 93(line=5, offs=17) -- 183(line=8, offs=27)
*/
ATSINSflab(__patsflab_maybe_bind):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 116(line=6, offs=2) -- 183(line=8, offs=27)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 132(line=7, offs=4) -- 141(line=7, offs=13)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 105(line=5, offs=29) -- 106(line=5, offs=30)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 141(line=7, offs=13) -- 141(line=7, offs=13)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 145(line=7, offs=17) -- 155(line=7, offs=27)
*/

ATSINSmove_nil(tmpret0) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 160(line=8, offs=4) -- 167(line=8, offs=11)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 105(line=5, offs=29) -- 106(line=5, offs=30)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 167(line=8, offs=11) -- 167(line=8, offs=11)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 166(line=8, offs=10) -- 167(line=8, offs=11)
*/
ATSINSmove(tmp1, ATSSELcon(arg0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 179(line=8, offs=23) -- 182(line=8, offs=26)
*/
ATSINSmove(tmp2, ATSfunclo_fun(arg1, (atstyvar_type(a)), atstyvar_type(b))(tmp1)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 173(line=8, offs=17) -- 182(line=8, offs=26)
*/

ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret0, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(tmpret0, 1) ;
#endif
ATSINSstore_con1_ofs(tmpret0, postiats_tysum_1, atslab__0, tmp2) ;
ATSINSmove_con1_end()
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_sats__maybe_bind__0] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 212(line=10, offs=26) -- 360(line=17, offs=3)
*/
/*
local: 
global: maybe_show$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(3842)
tmparg = S2Evar(a(3842))
tmpsub = None()
*/
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_sats__maybe_show__1(atstype_boxed arg0, atstype_funptr arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret3) ;
ATStmpdec(tmp4, atstyvar_type(a)) ;
// ATStmpdec_void(tmp5) ;
// ATStmpdec_void(tmp6) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 201(line=10, offs=15) -- 360(line=17, offs=3)
*/
ATSINSflab(__patsflab_maybe_show):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 224(line=11, offs=2) -- 360(line=17, offs=3)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 240(line=12, offs=4) -- 249(line=12, offs=13)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 213(line=10, offs=27) -- 214(line=10, offs=28)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab7) ; } ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 249(line=12, offs=13) -- 249(line=12, offs=13)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 253(line=12, offs=17) -- 267(line=12, offs=31)
*/
ATSINSmove_void(tmpret3, atspre_print_string(ATSPMVstring("Nothing"))) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 272(line=13, offs=4) -- 278(line=13, offs=10)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 213(line=10, offs=27) -- 214(line=10, offs=28)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 278(line=13, offs=10) -- 278(line=13, offs=10)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 277(line=13, offs=9) -- 278(line=13, offs=10)
*/
ATSINSmove(tmp4, ATSSELcon(arg0, postiats_tysum_2, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 283(line=13, offs=15) -- 360(line=17, offs=3)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 306(line=14, offs=12) -- 319(line=14, offs=25)
*/
ATSINSmove_void(tmp5, atspre_print_string(ATSPMVstring("Just ("))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 332(line=15, offs=12) -- 335(line=15, offs=15)
*/
ATSINSmove_void(tmp6, ATSfunclo_fun(arg1, (atstyvar_type(a)), atsvoid_t0ype)(tmp4)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 348(line=16, offs=12) -- 356(line=16, offs=20)
*/
ATSINSmove_void(tmpret3, atspre_print_string(ATSPMVstring(")"))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/ats-utils/maybe.dats: 283(line=13, offs=15) -- 360(line=17, offs=3)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret3) ;
} /* end of [_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_sats__maybe_show__1] */
#endif // end of [TEMPLATE]

#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_init(_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_ats_055_utils_057_maybe_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
