/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-5-13: 13h: 1m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/stat.sats: 1776(line=53, offs=1) -- 1818(line=54, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 15159(line=816, offs=1) -- 15189(line=816, offs=31)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/stream.dats: 1570(line=48, offs=1) -- 1609(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/stream_vt.dats: 1573(line=48, offs=1) -- 1612(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/home/hwwu/GitHub/lam-lite/untyped/name.sats: 1(line=1, offs=1) -- 30(line=1, offs=30)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_0 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tysum_1 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_eq_string_string)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_sats__name_eq(atstype_boxed, atstype_boxed) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_sats__name_show(atstype_boxed) ;
#endif // end of [QUALIFIED]

/*
/home/hwwu/GitHub/lam-lite/untyped/name.dats: 133(line=6, offs=19) -- 424(line=21, offs=16)
*/
/*
local: 
global: name_eq$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_bool)
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_sats__name_eq(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 125(line=6, offs=11) -- 424(line=21, offs=16)
*/
ATSINSflab(__patsflab_name_eq):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 144(line=7, offs=2) -- 424(line=21, offs=16)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 159(line=8, offs=4) -- 166(line=8, offs=11)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 134(line=6, offs=20) -- 135(line=6, offs=21)
*/
ATSifnthen(ATSCKpat_con0(arg0, 2)) { ATSINSgoto(__atstmplab2) ; } ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 166(line=8, offs=11) -- 166(line=8, offs=11)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 174(line=9, offs=3) -- 219(line=11, offs=15)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 190(line=10, offs=5) -- 196(line=10, offs=11)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 137(line=6, offs=23) -- 138(line=6, offs=24)
*/
ATSifnthen(ATSCKpat_con0(arg1, 2)) { ATSINSgoto(__atstmplab8) ; } ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 196(line=10, offs=11) -- 196(line=10, offs=11)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 200(line=10, offs=15) -- 204(line=10, offs=19)
*/
ATSINSmove(tmpret0, ATSPMVbool_true()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 210(line=11, offs=6) -- 210(line=11, offs=6)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 214(line=11, offs=10) -- 219(line=11, offs=15)
*/
ATSINSmove(tmpret0, ATSPMVbool_false()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 227(line=13, offs=4) -- 235(line=13, offs=12)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 134(line=6, offs=20) -- 135(line=6, offs=21)
*/
ATSifnthen(ATSCKpat_con1(arg0, 0)) { ATSINSgoto(__atstmplab4) ; } ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 235(line=13, offs=12) -- 235(line=13, offs=12)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 233(line=13, offs=10) -- 235(line=13, offs=12)
*/
ATSINSmove(tmp1, ATSSELcon(arg0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 244(line=14, offs=3) -- 319(line=16, offs=15)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 260(line=15, offs=5) -- 268(line=15, offs=13)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 137(line=6, offs=23) -- 138(line=6, offs=24)
*/
ATSifnthen(ATSCKpat_con1(arg1, 0)) { ATSINSgoto(__atstmplab11) ; } ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 268(line=15, offs=13) -- 268(line=15, offs=13)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 266(line=15, offs=11) -- 268(line=15, offs=13)
*/
ATSINSmove(tmp3, ATSSELcon(arg1, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 276(line=15, offs=21) -- 283(line=15, offs=28)
*/
ATSINSmove(tmp4, atspre_eq_string_string(tmp1, tmp3)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 273(line=15, offs=18) -- 304(line=15, offs=49)
*/
ATSif(
tmp4
) ATSthen() {
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 289(line=15, offs=34) -- 293(line=15, offs=38)
*/
ATSINSmove(tmpret0, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 299(line=15, offs=44) -- 304(line=15, offs=49)
*/
ATSINSmove(tmpret0, ATSPMVbool_false()) ;
} /* ATSendif */
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 310(line=16, offs=6) -- 310(line=16, offs=6)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 314(line=16, offs=10) -- 319(line=16, offs=15)
*/
ATSINSmove(tmpret0, ATSPMVbool_false()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 328(line=18, offs=4) -- 337(line=18, offs=13)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 134(line=6, offs=20) -- 135(line=6, offs=21)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(arg0, 1)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 337(line=18, offs=13) -- 337(line=18, offs=13)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 335(line=18, offs=11) -- 337(line=18, offs=13)
*/
ATSINSmove(tmp2, ATSSELcon(arg0, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 345(line=19, offs=4) -- 424(line=21, offs=16)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 362(line=20, offs=6) -- 371(line=20, offs=15)
*/
ATSINSlab(__atstmplab12):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 137(line=6, offs=23) -- 138(line=6, offs=24)
*/
ATSifnthen(ATSCKpat_con1(arg1, 1)) { ATSINSgoto(__atstmplab14) ; } ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 371(line=20, offs=15) -- 371(line=20, offs=15)
*/
ATSINSlab(__atstmplab13):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 369(line=20, offs=13) -- 371(line=20, offs=15)
*/
ATSINSmove(tmp5, ATSSELcon(arg1, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 379(line=20, offs=23) -- 386(line=20, offs=30)
*/
ATSINSmove(tmp6, ATSLIB_056_prelude__eq_g0int_int__1__1(tmp2, tmp5)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 376(line=20, offs=20) -- 407(line=20, offs=51)
*/
ATSif(
tmp6
) ATSthen() {
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 392(line=20, offs=36) -- 396(line=20, offs=40)
*/
ATSINSmove(tmpret0, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 402(line=20, offs=46) -- 407(line=20, offs=51)
*/
ATSINSmove(tmpret0, ATSPMVbool_false()) ;
} /* ATSendif */
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 415(line=21, offs=7) -- 415(line=21, offs=7)
*/
ATSINSlab(__atstmplab14):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 419(line=21, offs=11) -- 424(line=21, offs=16)
*/
ATSINSmove(tmpret0, ATSPMVbool_false()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_sats__name_eq] */

#if(0)
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 29101(line=802, offs=14) -- 29141(line=802, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4441)
tmparg = S2Evar(tk(4441))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29088(line=802, offs=1) -- 29141(line=802, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29127(line=802, offs=40) -- 29139(line=802, offs=52)
*/
ATSINSmove(tmp8, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4441))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29110(line=802, offs=23) -- 29141(line=802, offs=54)
*/
ATSINSmove(tmpret7, PMVtmpltcst(g0int_eq<S2Evar(tk(4441))>)(arg0, tmp8)) ;

ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1] */
#endif // end of [TEMPLATE]

/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 29101(line=802, offs=14) -- 29141(line=802, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4441)
tmparg = S2Evar(tk(4441))
tmpsub = Some(tk(4441) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29088(line=802, offs=1) -- 29141(line=802, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29127(line=802, offs=40) -- 29139(line=802, offs=52)
*/
ATSINSmove(tmp8__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29110(line=802, offs=23) -- 29141(line=802, offs=54)
*/
ATSINSmove(tmpret7__1, atspre_g0int_eq_int(arg0, tmp8__1)) ;

ATSfunbody_end()
ATSreturn(tmpret7__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__1] */

/*
/home/hwwu/GitHub/lam-lite/untyped/name.dats: 447(line=24, offs=21) -- 524(line=28, offs=16)
*/
/*
local: 
global: name_show$5$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_sats__name_show(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret11) ;
ATStmpdec(tmp12, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 437(line=24, offs=11) -- 524(line=28, offs=16)
*/
ATSINSflab(__patsflab_name_show):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 455(line=25, offs=2) -- 524(line=28, offs=16)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 470(line=26, offs=4) -- 476(line=26, offs=10)
*/
ATSINSlab(__atstmplab15):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 448(line=24, offs=22) -- 449(line=24, offs=23)
*/
ATSifnthen(ATSCKpat_con1(arg0, 0)) { ATSINSgoto(__atstmplab17) ; } ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 476(line=26, offs=10) -- 476(line=26, offs=10)
*/
ATSINSlab(__atstmplab16):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 475(line=26, offs=9) -- 476(line=26, offs=10)
*/
ATSINSmove(tmp12, ATSSELcon(arg0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 481(line=26, offs=15) -- 487(line=26, offs=21)
*/
ATSINSmove_void(tmpret11, atspre_print_string(tmp12)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 491(line=27, offs=4) -- 498(line=27, offs=11)
*/
ATSINSlab(__atstmplab17):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 448(line=24, offs=22) -- 449(line=24, offs=23)
*/
ATSifnthen(ATSCKpat_con1(arg0, 1)) { ATSINSgoto(__atstmplab19) ; } ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 498(line=27, offs=11) -- 498(line=27, offs=11)
*/
ATSINSlab(__atstmplab18):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 497(line=27, offs=10) -- 498(line=27, offs=11)
*/
ATSINSmove(tmp13, ATSSELcon(arg0, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 502(line=27, offs=15) -- 508(line=27, offs=21)
*/
ATSINSmove_void(tmpret11, atspre_print_int(tmp13)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 512(line=28, offs=4) -- 518(line=28, offs=10)
*/
ATSINSlab(__atstmplab19):
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 448(line=24, offs=22) -- 449(line=24, offs=23)
*/
#if(0)
ATSifnthen(ATSCKpat_con0(arg0, 2)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 518(line=28, offs=10) -- 518(line=28, offs=10)
*/
ATSINSlab(__atstmplab20):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/lam-lite/untyped/name.dats: 522(line=28, offs=14) -- 524(line=28, offs=16)
*/
ATSINSmove_void(tmpret11, ATSPMVempty()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret11) ;
} /* end of [_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_sats__name_show] */

#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_init(_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hwwu_057_GitHub_057_lam_055_lite_057_untyped_057_name_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
